import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppToaster } from "../components/ui/toaster";
import { ThemeProvider } from "../components/theme/ThemeProvider";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product Catalog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh bg-linear-to-b from-background to-muted/40`}
      >
        <ThemeProvider>
          <Header />
          <div className="min-h-dvh pt-6">
            {children}
          </div>
          <AppToaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
